[package]
name = "keri-neon"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
keri = { git = "https://github.com/decentralized-identity/keriox" }
tempfile = "3.1"
thiserror = "1.0"
base64 = "0.13.0"
napi = "1"
napi-derive = "1"
simple_config_parser = "0.1.5"

[target.'cfg(all(any(windows, unix), target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true