[package]
name = "keri-neon"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
keri =  { git = "https://github.com/THCLab/keriox.git", branch="update_message_builder"} 
thiserror = "1.0"
base64 = "0.13.0"
napi = { version = "1", features = ["serde-json"]}
napi-derive = "1"
simple_config_parser = "0.1.5"

[target.'cfg(all(any(windows, unix), target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true

[dev-dependencies]
ed25519-compact = "0.1"
tempfile = "3.1"