name: keri_android
description: Keri plugin implementation for Android
version: 0.0.1
repository: https://github.com/THCLab/keri-bindings/tree/master/bindings/dart/keri/keri_android

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.49.2
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  keri_platform_interface: ^0.0.2
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.thclab.keri_android
        pluginClass: KeriAndroidPlugin
        dartPluginClass: KeriAndroid
