name: keri_android
description: Keri plugin implementation for Android devices only. See keri for all types.
version: 1.1.1
repository: https://github.com/THCLab/keri-bindings/tree/master/bindings/dart/keri/keri_android

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  build_runner: ^2.3.2
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.82.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.2.0
  keri_platform_interface: ^1.0.3
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.0.1


flutter:
  plugin:
    implements: keri
    platforms:
      android:
        package: com.thclab.keri_android
        pluginClass: KeriAndroidPlugin
        dartPluginClass: KeriAndroid
