[package]
name = "keri-neon"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
keri = { git = "https://github.com/decentralized-identity/keriox" }
tempfile = "3.1"
neon = "0.9"
thiserror = "1.0"
base64 = "0.13.0"
