name: keri_platform_interface
description: A common platform interface for the Keri plugin.
version: 0.0.4
repository: https://github.com/THCLab/keri-bindings/tree/master/bindings/dart/keri

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.49.2
  freezed: ^2.1.0+1
  freezed_annotation: ^2.2.0
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


