name: keri
description: Dart client for managing KERI based Identifiers on Android system.
version: 1.0.0
homepage: https://github.com/THCLab/keri-bindings/tree/master/bindings/dart/keri

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.48.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.2.0
  keri_android: ^0.0.3
  keri_platform_interface: ^0.0.3
  keri_windows: ^0.0.3
  meta: ^1.7.0
  path: ^1.8.1
  plugin_platform_interface: ^2.1.3
  test: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.1.2
  build_runner: ^2.2.1


flutter:
  plugin:
    platforms:
      android:
        default_package: keri_android
      ios:
        pluginClass: KeriPlugin
      windows:
        default_package: keri_windows
      macos:
        pluginClass: KeriPlugin
