name: keri
description: Dart client for managing KERI based Identifiers on Android system.
version: 1.2.4
homepage: https://github.com/THCLab/keri-bindings/tree/master/bindings/dart/keri/keri

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.51.0
  keri_android: ^0.0.10
  keri_ios: ^0.0.4
  keri_macos: ^0.0.2
  keri_platform_interface: ^0.0.5
  keri_windows: ^0.0.6
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.1.2
  build_runner: ^2.2.1


flutter:
  plugin:
    platforms:
      android:
        default_package: keri_android
      ios:
        default_package: keri_ios
      windows:
        default_package: keri_windows
      macos:
        default_package: keri_macos
