[package]
name = "keri-dart"
version = "0.1.0"
edition = "2021"

[lib]
name = "dartkeriox"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutter_rust_bridge = "1.23.0"
keri = { git = "https://github.com/THCLab/keriox.git", branch = "controller_module", features = ["controller"] }
anyhow = { version = "1.0.56", features = ["backtrace"] }
thiserror = "1.0.30"
base64 = "0.13.0"
hex = "0.4.3"
futures = "0.3"
serde_json = "1.0.81"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.1"