name: keri_ios
description: Keri plugin implementation for iOS devices only. See keri for all types.
version: 0.2.3
repository: https://github.com/THCLab/keri-bindings/tree/master/bindings/dart/keri/keri_ios

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  build_runner: ^2.3.2
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.71.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.2.0
  keri_platform_interface: ^1.0.3
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^7.2.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: KeriIosPlugin
        dartPluginClass: KeriIos


