#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    non_snake_case
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

use crate::api::*;
use flutter_rust_bridge::*;

// Section: imports

// Section: wire functions

#[no_mangle]
pub extern "C" fn wire_with_initial_oobis(
    port_: i64,
    config: *mut wire_Config,
    oobis_json: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "with_initial_oobis",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_config = config.wire2api();
            let api_oobis_json = oobis_json.wire2api();
            move |task_callback| Ok(with_initial_oobis(api_config, api_oobis_json))
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_init_kel(
    port_: i64,
    input_app_dir: *mut wire_uint_8_list,
    optional_configs: *mut wire_Config,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "init_kel",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_input_app_dir = input_app_dir.wire2api();
            let api_optional_configs = optional_configs.wire2api();
            move |task_callback| init_kel(api_input_app_dir, api_optional_configs)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_incept(
    port_: i64,
    public_keys: *mut wire_list_public_key,
    next_pub_keys: *mut wire_list_public_key,
    witnesses: *mut wire_StringList,
    witness_threshold: u64,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "incept",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_public_keys = public_keys.wire2api();
            let api_next_pub_keys = next_pub_keys.wire2api();
            let api_witnesses = witnesses.wire2api();
            let api_witness_threshold = witness_threshold.wire2api();
            move |task_callback| {
                incept(
                    api_public_keys,
                    api_next_pub_keys,
                    api_witnesses,
                    api_witness_threshold,
                )
            }
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_finalize_inception(
    port_: i64,
    event: *mut wire_uint_8_list,
    signature: *mut wire_Signature,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "finalize_inception",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_event = event.wire2api();
            let api_signature = signature.wire2api();
            move |task_callback| finalize_inception(api_event, api_signature)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_rotate(
    port_: i64,
    controller: *mut wire_Controller,
    current_keys: *mut wire_list_public_key,
    new_next_keys: *mut wire_list_public_key,
    witness_to_add: *mut wire_StringList,
    witness_to_remove: *mut wire_StringList,
    witness_threshold: u64,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "rotate",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_controller = controller.wire2api();
            let api_current_keys = current_keys.wire2api();
            let api_new_next_keys = new_next_keys.wire2api();
            let api_witness_to_add = witness_to_add.wire2api();
            let api_witness_to_remove = witness_to_remove.wire2api();
            let api_witness_threshold = witness_threshold.wire2api();
            move |task_callback| {
                rotate(
                    api_controller,
                    api_current_keys,
                    api_new_next_keys,
                    api_witness_to_add,
                    api_witness_to_remove,
                    api_witness_threshold,
                )
            }
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_anchor(
    port_: i64,
    controller: *mut wire_Controller,
    data: *mut wire_uint_8_list,
    algo: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "anchor",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_controller = controller.wire2api();
            let api_data = data.wire2api();
            let api_algo = algo.wire2api();
            move |task_callback| anchor(api_controller, api_data, api_algo)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_anchor_digest(
    port_: i64,
    controller: *mut wire_Controller,
    sais: *mut wire_StringList,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "anchor_digest",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_controller = controller.wire2api();
            let api_sais = sais.wire2api();
            move |task_callback| anchor_digest(api_controller, api_sais)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_add_watcher(
    port_: i64,
    controller: *mut wire_Controller,
    watcher_oobi: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "add_watcher",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_controller = controller.wire2api();
            let api_watcher_oobi = watcher_oobi.wire2api();
            move |task_callback| add_watcher(api_controller, api_watcher_oobi)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_finalize_event(
    port_: i64,
    identifier: *mut wire_Controller,
    event: *mut wire_uint_8_list,
    signature: *mut wire_Signature,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "finalize_event",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_identifier = identifier.wire2api();
            let api_event = event.wire2api();
            let api_signature = signature.wire2api();
            move |task_callback| finalize_event(api_identifier, api_event, api_signature)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_resolve_oobi(port_: i64, oobi_json: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "resolve_oobi",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_oobi_json = oobi_json.wire2api();
            move |task_callback| resolve_oobi(api_oobi_json)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_query(
    port_: i64,
    controller: *mut wire_Controller,
    oobis_json: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "query",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_controller = controller.wire2api();
            let api_oobis_json = oobis_json.wire2api();
            move |task_callback| query(api_controller, api_oobis_json)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_process_stream(port_: i64, stream: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "process_stream",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_stream = stream.wire2api();
            move |task_callback| process_stream(api_stream)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_get_kel(port_: i64, cont: *mut wire_Controller) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_kel",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_cont = cont.wire2api();
            move |task_callback| get_kel(api_cont)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_get_kel_by_str(port_: i64, cont_id: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_kel_by_str",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_cont_id = cont_id.wire2api();
            move |task_callback| get_kel_by_str(api_cont_id)
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_get_current_public_key(port_: i64, attachment: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_current_public_key",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_attachment = attachment.wire2api();
            move |task_callback| get_current_public_key(api_attachment)
        },
    )
}

// Section: wire structs

#[repr(C)]
#[derive(Clone)]
pub struct wire_StringList {
    ptr: *mut *mut wire_uint_8_list,
    len: i32,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_Config {
    initial_oobis: *mut wire_uint_8_list,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_Controller {
    identifier: *mut wire_uint_8_list,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_list_public_key {
    ptr: *mut wire_PublicKey,
    len: i32,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_PublicKey {
    algorithm: i32,
    key: *mut wire_uint_8_list,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_Signature {
    algorithm: i32,
    key: *mut wire_uint_8_list,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_uint_8_list {
    ptr: *mut u8,
    len: i32,
}

// Section: wrapper structs

// Section: static checks

// Section: allocate functions

#[no_mangle]
pub extern "C" fn new_StringList(len: i32) -> *mut wire_StringList {
    let wrap = wire_StringList {
        ptr: support::new_leak_vec_ptr(<*mut wire_uint_8_list>::new_with_null_ptr(), len),
        len,
    };
    support::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn new_box_autoadd_config() -> *mut wire_Config {
    support::new_leak_box_ptr(wire_Config::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn new_box_autoadd_controller() -> *mut wire_Controller {
    support::new_leak_box_ptr(wire_Controller::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn new_box_autoadd_signature() -> *mut wire_Signature {
    support::new_leak_box_ptr(wire_Signature::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn new_list_public_key(len: i32) -> *mut wire_list_public_key {
    let wrap = wire_list_public_key {
        ptr: support::new_leak_vec_ptr(<wire_PublicKey>::new_with_null_ptr(), len),
        len,
    };
    support::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn new_uint_8_list(len: i32) -> *mut wire_uint_8_list {
    let ans = wire_uint_8_list {
        ptr: support::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    support::new_leak_box_ptr(ans)
}

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        if self.is_null() {
            None
        } else {
            Some(self.wire2api())
        }
    }
}

impl Wire2Api<String> for *mut wire_uint_8_list {
    fn wire2api(self) -> String {
        let vec: Vec<u8> = self.wire2api();
        String::from_utf8_lossy(&vec).into_owned()
    }
}

impl Wire2Api<Vec<String>> for *mut wire_StringList {
    fn wire2api(self) -> Vec<String> {
        let vec = unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(Wire2Api::wire2api).collect()
    }
}

impl Wire2Api<Config> for *mut wire_Config {
    fn wire2api(self) -> Config {
        let wrap = unsafe { support::box_from_leak_ptr(self) };
        (*wrap).wire2api().into()
    }
}

impl Wire2Api<Controller> for *mut wire_Controller {
    fn wire2api(self) -> Controller {
        let wrap = unsafe { support::box_from_leak_ptr(self) };
        (*wrap).wire2api().into()
    }
}

impl Wire2Api<Signature> for *mut wire_Signature {
    fn wire2api(self) -> Signature {
        let wrap = unsafe { support::box_from_leak_ptr(self) };
        (*wrap).wire2api().into()
    }
}

impl Wire2Api<Config> for wire_Config {
    fn wire2api(self) -> Config {
        Config {
            initial_oobis: self.initial_oobis.wire2api(),
        }
    }
}

impl Wire2Api<Controller> for wire_Controller {
    fn wire2api(self) -> Controller {
        Controller {
            identifier: self.identifier.wire2api(),
        }
    }
}

impl Wire2Api<DigestType> for i32 {
    fn wire2api(self) -> DigestType {
        match self {
            0 => DigestType::Blake3_256,
            1 => DigestType::SHA3_256,
            2 => DigestType::SHA2_256,
            3 => DigestType::Blake3_512,
            4 => DigestType::SHA3_512,
            5 => DigestType::Blake2B512,
            6 => DigestType::SHA2_512,
            _ => unreachable!("Invalid variant for DigestType: {}", self),
        }
    }
}

impl Wire2Api<KeyType> for i32 {
    fn wire2api(self) -> KeyType {
        match self {
            0 => KeyType::ECDSAsecp256k1,
            1 => KeyType::Ed25519,
            2 => KeyType::Ed448,
            3 => KeyType::X25519,
            4 => KeyType::X448,
            _ => unreachable!("Invalid variant for KeyType: {}", self),
        }
    }
}

impl Wire2Api<Vec<PublicKey>> for *mut wire_list_public_key {
    fn wire2api(self) -> Vec<PublicKey> {
        let vec = unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(Wire2Api::wire2api).collect()
    }
}

impl Wire2Api<PublicKey> for wire_PublicKey {
    fn wire2api(self) -> PublicKey {
        PublicKey {
            algorithm: self.algorithm.wire2api(),
            key: self.key.wire2api(),
        }
    }
}

impl Wire2Api<Signature> for wire_Signature {
    fn wire2api(self) -> Signature {
        Signature {
            algorithm: self.algorithm.wire2api(),
            key: self.key.wire2api(),
        }
    }
}

impl Wire2Api<SignatureType> for i32 {
    fn wire2api(self) -> SignatureType {
        match self {
            0 => SignatureType::Ed25519Sha512,
            1 => SignatureType::ECDSAsecp256k1Sha256,
            2 => SignatureType::Ed448,
            _ => unreachable!("Invalid variant for SignatureType: {}", self),
        }
    }
}

impl Wire2Api<u64> for u64 {
    fn wire2api(self) -> u64 {
        self
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
    fn wire2api(self) -> Vec<u8> {
        unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}

// Section: impl NewWithNullPtr

pub trait NewWithNullPtr {
    fn new_with_null_ptr() -> Self;
}

impl<T> NewWithNullPtr for *mut T {
    fn new_with_null_ptr() -> Self {
        std::ptr::null_mut()
    }
}

impl NewWithNullPtr for wire_Config {
    fn new_with_null_ptr() -> Self {
        Self {
            initial_oobis: core::ptr::null_mut(),
        }
    }
}

impl NewWithNullPtr for wire_Controller {
    fn new_with_null_ptr() -> Self {
        Self {
            identifier: core::ptr::null_mut(),
        }
    }
}

impl NewWithNullPtr for wire_PublicKey {
    fn new_with_null_ptr() -> Self {
        Self {
            algorithm: Default::default(),
            key: core::ptr::null_mut(),
        }
    }
}

impl NewWithNullPtr for wire_Signature {
    fn new_with_null_ptr() -> Self {
        Self {
            algorithm: Default::default(),
            key: core::ptr::null_mut(),
        }
    }
}

// Section: impl IntoDart

impl support::IntoDart for Config {
    fn into_dart(self) -> support::DartCObject {
        vec![self.initial_oobis.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Config {}

impl support::IntoDart for Controller {
    fn into_dart(self) -> support::DartCObject {
        vec![self.identifier.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Controller {}

impl support::IntoDart for KeyType {
    fn into_dart(self) -> support::DartCObject {
        match self {
            Self::ECDSAsecp256k1 => 0,
            Self::Ed25519 => 1,
            Self::Ed448 => 2,
            Self::X25519 => 3,
            Self::X448 => 4,
        }
        .into_dart()
    }
}

impl support::IntoDart for PublicKey {
    fn into_dart(self) -> support::DartCObject {
        vec![self.algorithm.into_dart(), self.key.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for PublicKey {}

impl support::IntoDart for PublicKeySignaturePair {
    fn into_dart(self) -> support::DartCObject {
        vec![self.key.into_dart(), self.signature.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for PublicKeySignaturePair {}

impl support::IntoDart for Signature {
    fn into_dart(self) -> support::DartCObject {
        vec![self.algorithm.into_dart(), self.key.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Signature {}

impl support::IntoDart for SignatureType {
    fn into_dart(self) -> support::DartCObject {
        match self {
            Self::Ed25519Sha512 => 0,
            Self::ECDSAsecp256k1Sha256 => 1,
            Self::Ed448 => 2,
        }
        .into_dart()
    }
}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

// Section: sync execution mode utility

#[no_mangle]
pub extern "C" fn free_WireSyncReturnStruct(val: support::WireSyncReturnStruct) {
    unsafe {
        let _ = support::vec_from_leak_ptr(val.ptr, val.len);
    }
}
