name: Node.js CI

on:
  push:
    branches: ["master"]
    paths:
      - "bindings/node.js/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["master"]
    paths:
      - "bindings/node.js/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./bindings/node.js

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: './bindings/node.js/package-lock.json'
      - run: npm ci
        working-directory: ./bindings/node.js
      - run: npm run test
        working-directory: ./bindings/node.js


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: './bindings/node.js/package-lock.json'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
